global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Edam.Data.Catalog.Console.DataContracts;
global using Edam.Data.Catalog.Console.DataContracts.Serialization;
global using Edam.Data.Catalog.Console.Models;
global using Edam.Data.Catalog.Console.Presentation;
global using Edam.Data.Catalog.Console.Services.Caching;
global using Edam.Data.Catalog.Console.Services.Endpoints;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
