global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Edam.Tests.CatalogExplorer.DataContracts;
global using Edam.Tests.CatalogExplorer.DataContracts.Serialization;
global using Edam.Tests.CatalogExplorer.Models;
global using Edam.Tests.CatalogExplorer.Presentation;
global using Edam.Tests.CatalogExplorer.Services.Caching;
global using Edam.Tests.CatalogExplorer.Services.Endpoints;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
